// <auto-generated />
namespace Challenger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialHierarchy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialHierarchy));
        
        string IMigrationMetadata.Id
        {
            get { return "201607080822547_InitialHierarchy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
